trigger:
  branches:
    include:
      - master
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-18.04'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'Install Dependencies'
      inputs:
        workingDir: '$(System.DefaultWorkingDirectory)'
        command: install

    - task: Npm@1
      displayName: 'Build App'
      inputs:
        workingDir: $(System.DefaultWorkingDirectory)'
        command: custom
        customCommand: run build-prod
        

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)\build'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true

    - task: PublishBuildArtifacts@1      
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'app'

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-18.04'
    variables:
      storageaccountname: staticwebsitedemostorage
    environment: 'Deploy Application'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: app
            
          - task: AzureFileCopy@3
            inputs:
              sourcePath: $(Pipeline.Workspace)/build
              azureSubscription: 'Azure Resource Management (PZ)'
              destination: azureBlob
              storage: $(storageAccount)
              containerName: "$web"